sudo: false

language: python

env:
  - SH=bash

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"

cache:
  pip: true
  directories:
    - $HOME/nltk_data

install:
  - "pip install -r ffscraper/tests/requirements.txt"
  - "python -m nltk.downloader stopwords punkt -d $HOME/nltk_data"

script:
  - coverage run ffscraper/tests/tests.py

before_install:
  export NLTK_DATA="$HOME/nltk_data";
  pip install codecov

after_success:
  codecov
