# Site settings
title: FicSearch
description: "A search and recommendation engine for FanFiction.Net"
url: "http://batflyer.net/"
author:
  name: "Alexander L. Hayes"
  email: "alexander@batflyer.net"
  url: "http://batflyer.net"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
